server:
  port: 9000
spring:
  application:
    name: gateway
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
