spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/innerpeacez/spring-cloud-config-learning.git
          username: innerpeacez
          password: zhwyj1019!
          searchPaths: /{application}
  application:
    name: config-server

server:
  port: 8888