spring:
  application:
    name: oauth2-server

server:
  port: 7777
  servlet:
    context-path: /uaa # web 基路径

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
